/**
 * Created by 40663 on 2018/8/15.
 */

module.exports = {
    'root':'nameXi',
    'content':[
        {
            'name':'views',
            'type':'dir'
        },
        {
            'name':'public',
            'type':'dir',
            'subdir':[
                {
                    'name':'css',
                    'type':'dir'
                },
                {
                    'name':'js',
                    'type':'dir'
                },
                {
                    'name':'img',
                    'type':'dir'
                }
            ]
        },
        {
            'name':'models',
            'type':'dir'
        },
        {
            'name':'index.html',
            'type':'file'
        },
        {
            'name':'app.js',
            'type':'file'
        },
        {
            'name':'404.html',
            'type':'file'
        }
    ]
}
